"""拆表

Revision ID: cd4f6ff8be63
Revises: 08afeea94657
Create Date: 2026-08-19 23:23:16.239704

"""
from typing import Sequence, Union
from snowflake_id_toolkit import TwitterSnowflakeIDGenerator
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'cd4f6ff8be63'
down_revision: Union[str, Sequence[str], None] = '08afeea94657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

generator = TwitterSnowflakeIDGenerator(node_id=0,epoch=int(datetime(2026,1,1,0,0,0).timestamp()*1000))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 建Tag表
    op.create_table(
        "tag",
        sa.Column("id", sa.BIGINT(), primary_key=True, autoincrement=False, nullable=False),
        sa.Column("tag_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # 建关联表
    op.create_table(
        "knowledge_tag",
        sa.Column("knowledge_id", sa.BIGINT(), sa.ForeignKey("knowledge.id")),
        sa.Column("tag_id", sa.BIGINT(), sa.ForeignKey("tag.id")),
    )

    # 开始迁移
    connection = op.get_bind()
    tag_cache = {}
    get_tags_sql = "SELECT knowledge.id, knowledge.tags FROM knowledge"
    insert_tag_sql = "INSERT INTO tag (id,tag_name) VALUES(:id,:tag_name)"
    insert_relation_sql = "INSERT INTO knowledge_tag (knowledge_id,tag_id) VALUES(:knowledge_id,:tag_id)"
    get_tagname_sql = "SELECT tag.id,tag.tag_name FROM tag"
    results = connection.execute(sa.text(get_tags_sql)).fetchall()
    for knowledge_id,tags in results:
        split_tags = tags.split(",")
        for tag in split_tags:
            if tag in tag_cache:
                tag_id = tag_cache.get("tag_name")
                connection.execute(sa.text(insert_relation_sql),{"knowledge_id":knowledge_id,"tag_id":tag_id})
            else:
                tagname_result = connection.execute(sa.text(get_tagname_sql)).fetchone()
                if tagname_result:
                    tag_id = tagname_result.id
                    connection.execute(sa.text(insert_relation_sql),{"knowledge_id":knowledge_id,"tag_id":tag_id})
                    tag_cache[tag] = tag_id
                else:
                    tag_id = generator.generate_next_id()
                    print(f"tag_id33{tag_id}")
                    connection.execute(sa.text(insert_tag_sql),{"id":tag_id,"tag_name":tag})
                    connection.execute(sa.text(insert_relation_sql),{"knowledge_id":knowledge_id,"tag_id":tag_id})
                    tag_cache[tag] = tag_id


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('knowledge_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_pkey'))
    )
    # ### end Alembic commands ###
