apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  label:
    run: frontend
spec:
  ports: 
  - port: 5173
    protocol: TCP
  selector:
    run: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: crpi-dnik4qqp3fmowxt1.cn-hangzhou.personal.cr.aliyuncs.com/agent_wu/agent:latest
        ports: 
        - containerPort: 3000
        command: ["npm","run","dev"]
      
